### PR TITLE
test: add automatic unit test detection of missing configuration to environment variable mapping

### LINKED ISSUE #420: test: add automatic unit test detection of missing configuration to environment variable mapping
## Story

**AS A** - developer
**I WANT** - to have automatic tests that would let me know when I create a new configuration and fail to create the environment variable mapping for it
**SO THAT** - I will not miss to add any configurations

## Tech Notes

- make a test that will be able to:
  - verify the correct usage and declaration of any configuration record
  - proactively fail and notify when we have added a configuration that has not the matching environment variable mapping

### PR DESCRIPTION
**Pull request by ata-nas**
**Description**:

- make a test that will be able to:
  - verify the correct usage and declaration of any configuration record
  - proactively fail and notify when we have added a configuration that has not the matching environment variable mapping

**Related issue(s)**:

Fixes #420 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: server/src/test/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializerTest.java [hunk 1]
```diff
@@ -71,35 +93,46 @@ class ServerMappedConfigSourceInitializerTest {
...
                             .findFirst();
                     assertThat(matchingMapping)
                             .isNotNull()
                             .withFailMessage(
                                     "Field [%s] in [%s] is not present in the environment variable mappings! Expected config key [%s] to be present and to be mapped to [%s]",
-                                    recordComponent.getName(),
+                                    fieldName,
                                     config.getSimpleName(),
                                     expectedMappedName,
                                     transformToEnvVarConvention(expectedMappedName))
```
Comment (georgi-l95) [inline server/src/test/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializerTest.java:138]: nit: This could be extracted in a variable with descriptive name.

**Review by georgi-l95 — APPROVED** [review]
LG

File: server/src/test/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializerTest.java (hunk 1 above)
Comment (ata-nas) [reply server/src/test/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializerTest.java:139]: ✅ Done. Thanks, I've missed that. Updated.

**Review by georgi-l95 — APPROVED** [review]

**Review by mattp-swirldslabs — APPROVED** [review]
Looks good. Thanks for adding this!
